[~, XTrain, Ytraining_regression, XValidation, YValidation] = Data_Generation(0.95, 30, 75000);

% Set up layers
Layers = [
    imageInputLayer([256 1 1],"Name","imageinput","Normalization","none")
    fullyConnectedLayer(500,"Name","fc_1")
    reluLayer("Name","relu_1")
    fullyConnectedLayer(250,"Name","fc_2")
    reluLayer("Name","relu_2")
    fullyConnectedLayer(120,"Name","fc_3")
    reluLayer("Name","relu_3")
    fullyConnectedLayer(16,"Name","fc_4")
    regressionLayer("Name","regressionoutput")];

% Option settings
ValidationFrequency = 500;
%3 2 % 0.7 0.8
Options = trainingOptions('rmsprop', ...
    'MaxEpochs',13, ...
    'MiniBatchSize',10, ...
    'InitialLearnRate',1e-3, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.8, ...
    'LearnRateDropPeriod',2, ...
    'ValidationData',{XValidation,YValidation}, ...
    'ValidationFrequency',ValidationFrequency, ...
    'Shuffle','every-epoch', ...
    'Verbose',1, ...
    'L2Regularization',0.003, ...
    'Plots','training-progress');

% Train Network
[DNN_Trained, info] = trainNetwork(XTrain, Ytraining_regression, Layers, Options);
