[XTrain, ~, YTrain_categorical, ~, ~, XValidation, YValidation_categorical, ~] = Data_Generation(0.95, 15, 50000);
Training_Set_Rate = 0.95;
% Set up layers
LSTM_Layers = [ ...
    sequenceInputLayer(256,"Name","sequence")
    lstmLayer(64,'OutputMode','last')
    fullyConnectedLayer(16)
    softmaxLayer("Name","softmax")
    classificationLayer('Name','classification')];

% Option settings
ValidationFrequency = ceil(1 / (1 - Training_Set_Rate));

Options = trainingOptions('adam', ...
    'MaxEpochs',15, ...
    'MiniBatchSize',10, ...
    'InitialLearnRate',2e-3, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.3, ...
    'LearnRateDropPeriod',4, ...
    'ValidationData',{XValidation,YValidation_categorical}, ...
    'ValidationFrequency',ValidationFrequency, ...
    'Shuffle','every-epoch', ...
    'Verbose',1, ...
    'L2Regularization',0.005, ...
    'Plots','training-progress');

% Train Network
[LSTM_Trained, info] = trainNetwork(XTrain, YTrain_categorical, LSTM_Layers, Options);
[XTest, ~, YTest_categorical, ~, ~, ~, ~, ~] = Data_Generation(1, 5, 10000);

Ypred = classify(LSTM_Trained, XTest);

SER = sum(Ypred ~= YTest_categorical) / numel(YTest_categorical);
